### ISSUE TITLE
pglogical build failed for Postgres 10

### ISSUE THREAD

**Issue by pashagolub** [2ndQuadrant/pglogical#160]
Hello.

Trying to build `pglogical/master` against `PostgreSQL 10.3` and got error:
```
pglogical_functions.c: In function ‘pglogical_drop_subscription’:
pglogical_functions.c:604:4: error: too few arguments to function ‘replorigin_drop’
    replorigin_drop(originid);
    ^
In file included from pglogical_functions.c:49:0:
```

**Comment by pashagolub** [comment]
@jbscalia please, try patched version https://github.com/pashagolub/pglogical

**Comment by jbscalia** [comment]
Pavel,

That fork still has the same problem. I’m looking at the PostgreSQL version 10.4 sources, and for instance, in the pglogical_apply_heap.c file, on line 626 is a call to ExecARDeleteTriggers, but it does not match the definition contained in src/include/commands/trigger.h. All the ExecAR commands now need TransitionStateChange parameter which was not present in the old 9.6 sources. At least I’m assuming so and I’m looking at the correct PostgreSQL sources.

I’ve successfully got pglogical working on both my 9.6.9 and 10.4 clusters, but I had to add a NULL pointer argument to the end of all the ExecAR functions in order to get them to compile for 10.4.

**Comment by pashagolub** [comment]
Yeap, I forgot to say you should use REL2.2-STABLE branch, master is far beyond it somehow. :(

**Comment by eulerto** [comment]
Current `pglogical` version builds just fine in all supported PostgreSQL versions.
