### ISSUE TITLE
Can't compile pglogical on Postgresql 9.4

### ISSUE THREAD

**Issue by gfnord** [2ndQuadrant/pglogical#106]
I can't compile pglogical with Postgresql 9.4, on Debian 8.

root@localhost # make USE_PGXS=1
pglogical_apply.o pglogical_conflict.o pglogical_manager.o pglogical.o pglogical_node.o pglogical_relcache.o pglogical_repset.o pglogical_rpc.o pglogical_functions.o pglogical_queue.o pglogical_fe.o pglogical_worker.o pglogical_sync.o pglogical_sequences.o pglogical_executor.o pglogical_dependency.o pglogical_apply_heap.o pglogical_apply_spi.o pglogical_output_config.o pglogical_output_plugin.o pglogical_output_proto.o pglogical_proto_json.o pglogical_proto_native.o /compat94/pglogical_compat.o
Makefile:86: warning: overriding recipe for target 'check'
/usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk:285: warning: ignoring old recipe for target 'check'
sed 's/__PGLOGICAL_VERSION__/2.0.0/;s/__REQUIRES__/requires=pglogical_origin/' /root/Downloads/pglogical/pglogical.control.in > /root/Downloads/pglogical/pglogical.control
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -fpic -shared -o pglogical.so pglogical_apply.o pglogical_conflict.o pglogical_manager.o pglogical.o pglogical_node.o pglogical_relcache.o pglogical_repset.o pglogical_rpc.o pglogical_functions.o pglogical_queue.o pglogical_fe.o pglogical_worker.o pglogical_sync.o pglogical_sequences.o pglogical_executor.o pglogical_dependency.o pglogical_apply_heap.o pglogical_apply_spi.o pglogical_output_config.o pglogical_output_plugin.o pglogical_output_proto.o pglogical_proto_json.o pglogical_proto_native.o .//compat94/pglogical_compat.o -L/usr/local/pgsql/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags  -L/usr/local/pgsql/lib -lpq
/bin/mkdir -p pglogical_dump
make -C pglogical_dump -f /root/Downloads/pglogical/pglogical_dump/Makefile VPATH=/root/Downloads/pglogical/pglogical_dump all
make[1]: Entering directory '/root/Downloads/pglogical/pglogical_dump'
make[1]: /root/Downloads/pglogical/pglogical_dump/Makefile: No such file or directory
make[1]: *** No rule to make target '/root/Downloads/pglogical/pglogical_dump/Makefile'.  Stop.
make[1]: Leaving directory '/root/Downloads/pglogical/pglogical_dump'
Makefile:179: recipe for target 'all-pglogical_dump-recurse' failed
make: *** [all-pglogical_dump-recurse] Error 2

There is the pg_config output:
db94:~/Downloads/pglogical# pg_config
BINDIR = /usr/local/pgsql/bin
DOCDIR = /usr/local/pgsql/share/doc
HTMLDIR = /usr/local/pgsql/share/doc
INCLUDEDIR = /usr/local/pgsql/include
PKGINCLUDEDIR = /usr/local/pgsql/include
INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
LIBDIR = /usr/local/pgsql/lib
PKGLIBDIR = /usr/local/pgsql/lib
LOCALEDIR = /usr/local/pgsql/share/locale
MANDIR = /usr/local/pgsql/share/man
SHAREDIR = /usr/local/pgsql/share
SYSCONFDIR = /usr/local/pgsql/etc
PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr/local/pgsql'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lz -lreadline -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 9.4.12

I successful compile against 9.6 and I noticed a couple different lines with pg_logical. 
in 9.4:
CPPFLAGS = -D_GNU_SOURCE
LDFLAGS = -L../../../src/common -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags

in 9.6:
CPPFLAGS = -DFRONTEND -D_GNU_SOURCE
LDFLAGS = -L../../src/common -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags

Since the directory structure is the same, I wonder why -L../../../src/common from pg_logical 9.4 is different from -L../../src/common from pg_logical 9.6.

Anyone has how to solve this?

Thanks.

**Comment by PJMODOS** [comment]
Looks like you are trying to compile git tree without updating submodules. Running something like following should make it work:
```
git submodule init
git submodule update
```

**Comment by infracaninophile** [comment]
This fails when compiling against postgresql9.4 with the source tarball downloaded from http://packages.2ndquadrant.com/pglogical/tarballs/pglogical-2.0.1.tar.bz2

**Comment by gfnord** [comment]
After update pglogical to 2.0.1, I got this error:

pglogical_apply_heap.c: In function ‘has_tuple_changed’:
pglogical_apply_heap.c:262:33: error: ‘SizeofHeapTupleHeader’ undeclared (first use in this function)
   memcmp(((char *) newheader) + SizeofHeapTupleHeader,
                                 ^
pglogical_apply_heap.c:262:33: note: each undeclared identifier is reported only once for each function it appears in
<builtin>: recipe for target 'pglogical_apply_heap.o' failed
make: *** [pglogical_apply_heap.o] Error 1

**Comment by PJMODOS** [comment]
Indeed, the wrong tar file was uploaded, fixed.

**Comment by PJMODOS** [comment]
Btw about the last error, that looks more like you are trying to compile master (that one is broken on 9.4 temporarily).
